# GitHub Pages configuration for PoC Research Papers

# Theme
theme: jekyll-theme-cayman
title: "PoC Research Papers"
description: 'A real-world Java vulnerability Benhamrk curated for our research paper "Comparison and Evaluation on Static Application Security Testing (SAST) Tools for Java"'
url: "https://marklee131.github.io"
baseurl: "/Java_CVE_Bench"

# SEO
lang: en-US
author: "Kaixuan Li"

# GitHub metadata
github:
  is_project_page: true
  repository_name: "Jaca_CVE_Bench"
  
# Enable plugins
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# File handling
include:
  - README.md

# Exclude from processing
exclude:
  - .gitignore
  - LICENSE
